### ISSUE TITLE
Practica 3 - Contrato compilado

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-9-contrato-compilado-equipopromastergamer777#1]
Subir la ultima practica.

**Comment by JoseABCruz** [comment]
[Práctica 3 Funcionalidad (José Antonio Balbuena Cruz).pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-contrato-compilado-equipopromastergamer777/files/11539314/Practica.3.Funcionalidad.Jose.Antonio.Balbuena.Cruz.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 3 Funcionalidad (Smart Contract) (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-contrato-compilado-equipopromastergamer777/files/11539316/Practica.3.Funcionalidad.Smart.Contract.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Práctica 3 Funcionalidad (Smart Contract).pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-contrato-compilado-equipopromastergamer777/files/11539493/Practica.3.Funcionalidad.Smart.Contract.pdf)

**Comment by SANDRAVELASCO** [comment]
[Practica.3.Funcionalidad(Sandra Gabriela Velasco Guzmán).pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-contrato-compilado-equipopromastergamer777/files/11539792/Practica.3.Funcionalidad.Sandra.Gabriela.Velasco.Guzman.pdf)

**Comment by EdwinOrtiz1412** [comment]
Calificacion: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
